
version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432" # Expose PostgreSQL port
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sensordata
    volumes:
      - ./timescaledb-data:/var/lib/postgresql/data # Persistent storage

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000" # Grafana web interface
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - timescaledb
    volumes:
      - grafana-data:/var/lib/grafana

   telegraf:
    image: telegraf
    container_name: telegraf
    environment:
      - TELEGRAF_INFLUXDB_URL=http://timescaledb:5432
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - timescaledb

volumes:
  grafana-data: