services:
  app:
    build: .
    container_name: smartbridge
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mosquitto
      - timescaledb

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /root/minimetrix/timescaledb-data:/var/lib/postgresql/data # Persistent storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    user: "$UID:$GID"
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - /root/minimetrix/grafana-data:/var/lib/grafana/

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - /root/minimetrix/mosquitto/config:/mosquitto/config
      - /root/minimetrix/mosquitto/data:/mosquitto/data
      - /root/minimetrix/mosquitto/log:/mosquitto/log

volumes:
  grafana-data:
  timescaledb:
  mosquitto: