
services:
  app:
    build: .
    container_name: smartbridge
    ports:
      - "${NODE_PORT}:${NODE_PORT}"  # Dynamically use the PORT variable from the .env file
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mosquitto
        # condition: service_healthy
      - timescaledb
        # condition: service_healthy

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432" # Expose PostgreSQL port
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ../timescaledb-data:/var/lib/postgresql/data # Persistent storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    user: "$UID:$GID"
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}" # Grafana web interface
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - ../grafana-data:/var/lib/grafana/

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    healthcheck:
      test: curl -f http://localhost:1883
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  grafana-data:
  timescaledb: